// Vendors tailwind-merge's default config (the semantic source of truth for
// which Tailwind classes exist and conflict) into a JSON marker-form module:
//   validator functions  → {$v: "name"}   (matched by identity)
//   theme getters        → {$t: "key"}    (key probed via a recording Proxy)
// Run after bumping the tailwind-merge devDependency; CI verifies freshness.
import { writeFileSync } from "node:fs"
import { getDefaultConfig, validators } from "tailwind-merge"

const config = getDefaultConfig()

const validatorByFn = new Map()
for (const [name, fn] of Object.entries(validators)) {
  if (typeof fn === "function") validatorByFn.set(fn, name)
}

const themeKeyOf = (getter) => {
  let key
  getter(
    new Proxy(
      {},
      {
        get: (_, k) => {
          key = String(k)
          return []
        },
      }
    )
  )
  if (!key) throw new Error("vendor-config: theme getter read no key")
  return key
}

const serializeDef = (def) => {
  if (typeof def === "string") return def
  if (typeof def === "function") {
    if (def.isThemeGetter === true) return { $t: themeKeyOf(def) }
    const name = validatorByFn.get(def)
    if (!name)
      throw new Error("vendor-config: unknown validator function in config")
    return { $v: name }
  }
  const out = {}
  for (const [k, v] of Object.entries(def)) out[k] = v.map(serializeDef)
  return out
}
const serializeGroups = (groups) => {
  const out = {}
  for (const [k, v] of Object.entries(groups)) out[k] = v.map(serializeDef)
  return out
}

const vendored = {
  theme: serializeGroups(config.theme),
  classGroups: serializeGroups(config.classGroups),
  conflictingClassGroups: config.conflictingClassGroups,
  conflictingClassGroupModifiers: config.conflictingClassGroupModifiers,
  orderSensitiveModifiers: config.orderSensitiveModifiers,
  postfixLookupClassGroups: config.postfixLookupClassGroups ?? [],
}

const json = JSON.stringify(vendored)
const groupIds = Object.keys(vendored.classGroups)
  .map((n) => JSON.stringify(n))
  .join(" | ")
const themeIds = Object.keys(vendored.theme)
  .map((n) => JSON.stringify(n))
  .join(" | ")
const out = `// GENERATED by scripts/vendor-config.mjs from tailwind-merge's default config
// (MIT, Dany Castillo — see README.md). Do not edit.
import type { CnConfig } from './compiler.js'

const J =
    ${JSON.stringify(json)}

/** A fresh copy of the default config (marker form; safe to mutate). */
export const getDefaultCnConfig = (): CnConfig => JSON.parse(J) as CnConfig

/** every class-group id in the default config (autocomplete for extensions) */
export type DefaultClassGroupIds = ${groupIds}

/** every theme scale key in the default config */
export type DefaultThemeGroupIds = ${themeIds}
`
writeFileSync(
  new URL("../../cn/src/default-config.generated.ts", import.meta.url),
  out
)
console.log(
  `vendored default config: ${Object.keys(vendored.classGroups).length} class groups, ${(json.length / 1024).toFixed(1)} KB json`
)
