// Regenerates src/tables.generated.ts (the default tables shipped in the
// package) from the vendored default config. Run `npm run build` first so
// dist/ exists, then this, then build again. CI verifies freshness.
import { writeFileSync } from 'node:fs'
import { compileToSource, compileStats } from '../dist/compiler.js'
import { defaultConfig } from '../dist/config.js'

const banner =
    '// GENERATED by scripts/compile-tables.mjs from the vendored default config. Do not edit.'
const source = compileToSource(defaultConfig(), { lang: 'ts', banner })
writeFileSync(new URL('../src/tables.generated.ts', import.meta.url), source)
const s = compileStats(defaultConfig())
console.log(
    `compiled: ${s.groups} groups, ${s.nodes} nodes, ${s.edges} edges, ` +
        `${s.liftedLiterals} lifted literals (${s.uniqueTails} tails), ` +
        `${(source.length / 1024).toFixed(1)} KB source`,
)
